language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=scraper
after_success:
  - coveralls
